#!/usr/bin/env node

import bcrypt from 'bcrypt'

const args = process.argv.slice(2);

if (args.length < 1) {
    console.log('Usage: hashpw user1:pw1 [user2:pw2 ...]')
    process.exit(1)
}

console.log('------------------ hashes pw -------------------')
args.forEach((pw, index, array) => {
    const [ user, pass ] = pw.split(':')
    const hash = bcrypt.hashSync(pass, 10)
    console.log(`USER_${String(user).toUpperCase()}=${user}:user:${hash}`)
    //console.log(user, pass, bcrypt.compareSync(pass,hash) )
})
console.log('------------------ hashes pw -------------------')
